2024-11-01 19:49:11,255 INFO: Video ID extraction result: kqwPR0da0FI [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:635]
2024-11-01 19:49:11,271 INFO: Existing summary found: False [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:646]
2024-11-01 19:49:11,271 INFO: Fetching video data for new summary [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:680]
2024-11-01 19:49:17,311 INFO: Video title: HISTORY OF IDEAS - Loneliness [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:690]
2024-11-01 19:49:17,311 INFO: Generating video summary [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:693]
2024-11-01 19:49:32,983 INFO: Successfully generated and parsed summary [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:699]
2024-11-01 19:49:33,009 INFO: New summary created with ID: 50 [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:719]
2024-11-01 19:49:33,010 INFO: Redirecting to: /dashboard?new_summary=50 [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:722]
2024-11-02 14:27:02,786 INFO: Lumina startup [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:51]
2024-11-02 14:28:48,422 INFO: Lumina startup [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:51]
2024-11-02 14:30:04,569 INFO: Lumina startup [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:51]
2024-11-02 14:30:23,546 INFO: Lumina startup [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:51]
2024-11-02 14:30:30,337 INFO: Lumina startup [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:51]
2024-11-02 14:30:49,332 INFO: Lumina startup [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:51]
2024-11-02 14:31:48,509 INFO: Lumina startup [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:51]
2024-11-02 14:31:56,627 ERROR: Error initiating OAuth flow: name 'google_auth_oauthlib' is not defined [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:411]
2024-11-02 14:32:00,416 ERROR: Error initiating OAuth flow: name 'google_auth_oauthlib' is not defined [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:411]
2024-11-02 14:34:49,203 INFO: Lumina startup [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:53]
2024-11-02 14:34:58,064 ERROR: Error initiating OAuth flow: name 'google_auth_oauthlib' is not defined [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:413]
2024-11-02 14:37:49,007 INFO: Lumina startup [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:58]
2024-11-02 14:37:54,107 INFO: Initiating YouTube OAuth flow for user 2 [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:404]
2024-11-02 14:45:54,647 INFO: Lumina startup [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:58]
2024-11-02 14:46:40,132 INFO: Initiating YouTube OAuth flow for user 1 [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:408]
2024-11-02 14:46:40,132 INFO: Redirect URI: https://localhost:5000/auth/youtube/callback [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:409]
2024-11-02 14:48:48,729 INFO: Lumina startup [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:58]
2024-11-02 14:48:54,705 INFO: Initiating YouTube OAuth flow for user 2 [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:402]
2024-11-02 14:48:54,705 INFO: Redirect URI: http://localhost:5000/auth/youtube/callback [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:403]
2024-11-02 14:49:12,124 ERROR: Error in oauth2callback: (mismatching_state) CSRF Warning! State not equal in request and response. [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:450]
2024-11-02 14:50:43,684 INFO: Lumina startup [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:58]
2024-11-02 14:50:48,454 INFO: Initiating YouTube OAuth flow for user 1 [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:403]
2024-11-02 14:50:48,455 INFO: Redirect URI: http://localhost:5000/auth/youtube/callback [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:404]
2024-11-02 14:50:48,455 INFO: State parameter: v7rJrS3nZnBvlNJUjEtGpnAWJ3BypS [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:405]
2024-11-02 14:50:55,101 INFO: State from session: v7rJrS3nZnBvlNJUjEtGpnAWJ3BypS [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:423]
2024-11-02 14:50:55,103 INFO: State from request: v7rJrS3nZnBvlNJUjEtGpnAWJ3BypS [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:424]
2024-11-02 15:02:57,202 INFO: Lumina startup [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:58]
2024-11-02 15:03:00,617 ERROR: Error in oauth2callback: No state in session [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:460]
2024-11-02 15:03:00,618 ERROR: Exception traceback:  [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:461]
Traceback (most recent call last):
  File "/Users/chrisbeaumont/Projects/YouTubeReports/app.py", line 417, in oauth2callback
    raise ValueError("No state in session")
ValueError: No state in session
2024-11-02 15:03:01,419 INFO: Initiating YouTube OAuth flow for user 1 [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:399]
2024-11-02 15:03:01,419 INFO: Redirect URI: http://localhost:5000/auth/youtube/callback [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:400]
2024-11-02 15:03:01,420 INFO: State parameter: K1LdyhMLC8ODjjn5HkESKV7PEAx2Nt [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:401]
2024-11-02 15:03:10,633 INFO: State from session: K1LdyhMLC8ODjjn5HkESKV7PEAx2Nt [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:419]
2024-11-02 15:03:10,633 INFO: State from request: K1LdyhMLC8ODjjn5HkESKV7PEAx2Nt [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:420]
2024-11-02 15:07:29,212 INFO: Lumina startup [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:58]
2024-11-02 15:07:31,618 ERROR: Error in oauth2callback: No state in session [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:470]
2024-11-02 15:07:31,619 ERROR: Exception traceback:  [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:471]
Traceback (most recent call last):
  File "/Users/chrisbeaumont/Projects/YouTubeReports/app.py", line 427, in oauth2callback
    raise ValueError("No state in session")
ValueError: No state in session
2024-11-02 15:07:32,479 INFO: Initiating YouTube OAuth flow for user 1 [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:410]
2024-11-02 15:07:32,479 INFO: Redirect URI: http://localhost:5000/auth/youtube/callback [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:411]
2024-11-02 15:07:32,479 INFO: State parameter: 8amEKeEeQ8l5iEUJMVlkr03hmhuX2Q [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:412]
2024-11-02 15:07:38,399 INFO: Starting OAuth callback processing [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:429]
2024-11-02 15:07:38,733 INFO: OAuth callback successful. Session ID: 461fe9a4-45e1-4c39-a254-f651eeb5aaf4 [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:457]
2024-11-02 15:07:38,734 INFO: Credentials stored in session: True [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:458]
2024-11-02 15:07:38,737 INFO: Template rendered, returning response [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:466]
2024-11-02 15:12:42,248 INFO: Lumina startup [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:58]
2024-11-02 15:12:46,250 INFO: Starting OAuth callback processing [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:432]
2024-11-02 15:12:46,465 ERROR: Error in oauth2callback: (invalid_grant) Bad Request [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:473]
2024-11-02 15:12:46,465 ERROR: Exception traceback:  [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:474]
Traceback (most recent call last):
  File "/Users/chrisbeaumont/Projects/YouTubeReports/app.py", line 443, in oauth2callback
    flow.fetch_token(authorization_response=authorization_response)
  File "/Users/chrisbeaumont/Projects/lumina/lib/python3.9/site-packages/google_auth_oauthlib/flow.py", line 285, in fetch_token
    return self.oauth2session.fetch_token(self.client_config["token_uri"], **kwargs)
  File "/Users/chrisbeaumont/Projects/lumina/lib/python3.9/site-packages/requests_oauthlib/oauth2_session.py", line 406, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/Users/chrisbeaumont/Projects/lumina/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 427, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/Users/chrisbeaumont/Projects/lumina/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 441, in parse_token_response
    validate_token_parameters(params)
  File "/Users/chrisbeaumont/Projects/lumina/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 448, in validate_token_parameters
    raise_from_error(params.get('error'), params)
  File "/Users/chrisbeaumont/Projects/lumina/lib/python3.9/site-packages/oauthlib/oauth2/rfc6749/errors.py", line 399, in raise_from_error
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidGrantError: (invalid_grant) Bad Request
2024-11-02 15:12:47,560 INFO: Initiating YouTube OAuth flow for user 1 [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:413]
2024-11-02 15:12:47,561 INFO: Redirect URI: http://localhost:5000/auth/youtube/callback [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:414]
2024-11-02 15:12:47,562 INFO: State parameter: rZCbzVG5Y2gNGMYh35e4dsWumOxI9I [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:415]
2024-11-02 15:12:54,347 INFO: Starting OAuth callback processing [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:432]
2024-11-02 15:12:54,580 INFO: OAuth callback successful. Session ID: c1f5c523-8690-4778-ba60-d48954b3a108 [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:460]
2024-11-02 15:12:54,580 INFO: Credentials stored in session: True [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:461]
2024-11-02 15:12:54,592 INFO: Template rendered, returning response [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:469]
2024-11-02 15:15:57,583 INFO: Starting OAuth callback processing [in /Users/chrisbeaumont/Projects/YouTubeReports/app.py:432]
